import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import MyNavbar from "@/app/components/MyNavbar";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <MyNavbar />
          <main className="min-h-screen">{children}</main>
          {/* <Footer /> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
